In [1]:
from __future__ import print_function
import numpy as np
from time import time # for comparing runing time
d, N = 10, 100 # 10 thông số, 100 dữ liệu
X = np.random.randn(N, d) # tạo ma trận ngẫu nhiên N hàng - d cột
Z = np.random.randn(50,d) #tạo ma trận 1 hàng, d cột

In [2]:
print(X)
print(Z)

[[-1.18630980e-01  5.49236097e-01 -8.83213695e-01 -1.28397564e+00
  -1.44311736e+00  7.48729220e-03 -3.08525523e-01  1.15786693e+00
   9.15368122e-01  2.22029828e+00]
 [-3.40511187e-01  1.29540473e+00  1.07205347e+00 -2.03392153e+00
   4.73790356e-01 -1.64643220e+00  8.94358875e-01 -7.60799313e-01
   4.09361031e-01 -9.56506575e-01]
 [-9.15622512e-02  1.92392814e-01 -4.04233729e-01  1.07398072e+00
   3.78886494e-01  7.25821660e-01  1.05157434e-01  4.50049109e-01
  -2.32656094e-01 -1.55079874e+00]
 [-1.68170483e+00 -1.90963163e+00 -7.86909720e-01 -2.04651071e-01
   2.77079195e-02  3.65094451e-02 -4.71051506e-01  1.89469704e-01
   1.04268573e+00 -1.01671359e+00]
 [ 1.74530288e-01 -1.05261071e+00 -1.65888327e+00 -6.29183366e-01
  -1.59678122e+00  2.16153015e+00 -3.58361094e-01  1.08840192e-01
   6.92577384e-01  1.80199003e+00]
 [-1.21389429e+00 -1.27343303e+00  1.36786564e+00 -1.96364686e+00
  -7.11419146e-01 -1.61483541e-01 -1.57973773e+00 -1.06347232e+00
   7.07590783e-01 -3.84373076e-01

In [3]:
def dist_pp(z, x):
    d = z - x.reshape(z.shape) # force x and z to have the same dims
    return np.sum(d*d)

In [5]:
dist_pp(Z,X[0])

ValueError: cannot reshape array of size 10 into shape (50,10)

In [10]:
X[0].reshape(z.shape)

array([-0.62478236,  0.45811172])

In [19]:
def dist_ps_naive(z, X):
    N = X.shape[0] #số hàng của X
    res = np.zeros((1, N)) #vector có N phần tử 0
    for i in range(N):
        res[0][i] = dist_pp(z, X[i])
    return res

In [14]:
X.shape[0]

10

In [15]:
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
dist_ps_naive(z, X)

IndexError: index 1 is out of bounds for axis 0 with size 1

In [29]:
# from one point to each point in a set, fast
def dist_ps_fast(z, X):
    X2 = np.sum(X*X, 1) # square of l2 norm of each X[i], can be precomputed
    z2 = np.sum(z*z) # square of l2 norm of z
    return X2 + z2 - 2*X.dot(z) # z2 can be ignored
t1 = time()
D1 = dist_ps_naive(z, X)
print(D1)
print('naive point2set, running time:', time() - t1, 's')
t1 = time()
D2 = dist_ps_fast(z, X)
print(D2)
print('fast point2set , running time:', time() - t1, 's')
print('Result difference:', np.linalg.norm(D1 - D2))

[[7.56353958 0.96529    1.01974009 9.16757051 6.41259891 4.92660034
  4.53369501 0.24753213 7.59089382 0.5764295 ]]
naive point2set, running time: 0.000997304916381836 s
[7.56353958 0.96529    1.01974009 9.16757051 6.41259891 4.92660034
 4.53369501 0.24753213 7.59089382 0.5764295 ]
fast point2set , running time: 0.0 s
Result difference: 9.805224261780596e-16


In [34]:
print(X)
print(z)
print(X.dot(2)) #X^T * z

[[-1.51199056  1.77356189]
 [-0.36202559 -0.08213343]
 [-0.46393182  0.00588674]
 [ 1.50427038  0.93868369]
 [ 1.25825872  0.42411703]
 [ 1.20328465 -0.1862696 ]
 [ 0.17849891  0.93140033]
 [-0.70745192 -1.36714903]
 [ 1.71447394 -0.02602104]
 [-0.49400682 -0.26277602]]
[-0.89611171 -0.90678003]
[[-3.02398112  3.54712378]
 [-0.72405118 -0.16426686]
 [-0.92786365  0.01177348]
 [ 3.00854076  1.87736737]
 [ 2.51651744  0.84823405]
 [ 2.40656929 -0.37253919]
 [ 0.35699782  1.86280065]
 [-1.41490385 -2.73429806]
 [ 3.42894787 -0.05204207]
 [-0.98801364 -0.52555205]]


In [ ]:

X.dot()